config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only:[:show]
  root "restaurants#index"


  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end


  resources :restaurants, only:[:index, :show] do
    resources :comments, only:[:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end
    
    member do
      get :dashboard

      post :favorite
      post :unfavorite

      post :like
      post :unlike
    end

  end  

  resources :users, only:[:index, :show, :edit, :update]

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }
  belongs_to :user
  belongs_to :following, class_name: "User"

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: { scope: :user_id }
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
  def is_liked?(user)
    self.liked_users.include?(user)
  end
  def favorite_number_count
    self.favorite_count = self.favorites.size
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validates_presence_of :name
  mount_uploader :avatar, AvatarUploader
  # 使用者評論很多餐廳 的多對多關聯
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments 

  # 使用者收藏很多餐廳的多對多關聯

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant
  #使用者追蹤使用者的多對多關係
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  #使用者想知道誰追蹤他的多對多關係
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user
  #使用者加別的使用者好友
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  #使用者知道誰加他好友的多對多關係
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user


  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def all_friends
    (friends + inverse_friends).uniq
  end

  def is_friend?(user)
    all_friends.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
protected

# Devise 客製化屬性的使用說明： https://github.com/plataformatec/devise#strong-parameters

def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.order(created_at: :desc).page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
   @restaurant = Restaurant.find(params[:restaurant_id])
   @comment = Comment.find(params[:id])

   if current_user.admin?
    @comment.destroy
    redirect_to restaurant_path(@restaurant)
   end
 end

private

 def comment_params
   params.require(:comment).permit(:content)
 end


end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    @followship = current_user.followships.build(following_id: params[:following_id])
    if @followship.save
      flash[:notice] = "成功追蹤"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end
  def destroy
    followship = Followship.where( user_id: current_user, following_id: params[:id]).first
    followship.destroy
    flash[:alert] = "你討厭他喔"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])

    if @friendship.save
      flash[:notice] = "已變成好友"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @friendship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end

  end

  def destroy
    @friendship = Friendship.where(user_id: current_user, friend_id: params[:id]).first
    @friendship.destroy
    flash[:alert] = "不跟你好惹"
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]
def show
  @comment_restaurants = @user.restaurants.uniq
  @favorited_restaurants = @user.favorited_restaurants.uniq
  @followings = @user.followings
  @followers = @user.followers
end
def edit
  unless @user == current_user
    redirect_to user_path(@user)
  end
end
def update
  @user.update(user_params)
  redirect_to user_path(current_user)
end

def index
  @users = User.all
end


private

def set_user
  @user = User.find(params[:id])
end

def user_params
  params.require(:user).permit(:name, :intro, :avatar)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1><%= "Edit Profile" %></h1>
<div class="form container">
  <%= form_for @user do |f|%>

  <div class="form-group">
    <h3><%= f.label :name, "Name" %></h3>
    <%= f.text_field :name , class: "form-control"%>
  </div>

  <div class="form-group">
    <h3><%= f.label :intro, "自我介紹" %></h3>
    <%= f.text_area :intro , class: "form-control"%>    
  </div>
  
  <div class="form-group">

    <h3><%= f.label :avatar, "大頭照上傳" %></h3>
    <%= image_tag @user.avatar, width: '300px' if @user.avatar? %>
    <%= f.file_field :avatar %>
  </div>
  <%= f.submit "Update" ,:class => 'btn btn-primary'%>
  <%= link_to 'Cancel', user_path(@user), :class => 'btn btn-default'%>
<% end %>

</div>    

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation" ><%= link_to "首頁", root_path %></li>
      <li role="presentation" ><%= link_to "最新動態", feeds_restaurants_path %></li>
      <li role="presentation" ><%= link_to "Top 10 人氣餐廳", ranking_restaurants_path %></li>
      <li role="presentation" class="active"><%= link_to "美食達人", users_path %></li>
    </ul>    
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">
        <h1>美食達人</h1>  
      </div>
    </div>

      <% @users.each do |user|%>
        <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
           
            <%= link_to user_path(user) do %>

              <%= image_tag(user.avatar, class: "img-rounded" ) %>
              <h4><%= user.name %></h4>      
            
          <% end %>     
          <%= render partial: "shared/follow", locals: {user: user} %>
          <%= render partial: "shared/friend", locals: {user: user} %>
        </div>

      <% end %>



  </div>
</div>
 

app/views/users/show.html.erb
    <div class="page-header">

       <div class="col-md-3 col-sm-4">
        <div class="text-center">
          <%= image_tag @user.avatar, class: "img-responsive img-circle" %>    
        </div>
      </div> 
      <div class="col-md-9 col-sm-8">
        <h1><%= @user.name %></h1>
        <h4><%= @user.email %></h4>
          <ul class="list-unstyled list-inline">
            <li><strong><%= @comment_restaurants.count %></strong> 個已評論餐廳</li>
            <li><strong><%= @favorited_restaurants.count %></strong> 個收藏的餐廳</li>
            <li><strong><%= @followings.count %></strong> followings</li>
            <li><strong><%= @followers.count %></strong> followers</li>
          </ul>
        <h5><%= @user.intro %></h5>    
        <%if @user.email == current_user.email %> 
        <%= link_to 'Edit Profile', edit_user_path(@user),:class => 'btn btn-primary'%>
        <% end %>  
      </div> 
      <div class="clearfix"></div> 
    </div>

<br>

<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @followings.count %>followings</h3>
    </div>
    <ul class="list-group">
      <% @followings.each do |following| %>
        <li class="list-group-item">
          <%= link_to user_path(following) do %>
            <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %>
            <%= following.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @followers.count %>followers</h3>
    </div>
    <ul class="list-group">
      <% @followers.each do |follower| %>
        <li class="list-group-item">
          <%= link_to user_path(follower) do %>
            <%= image_tag(follower.avatar, height: 30, width: 30, class: "img-circle") %>
            <%= follower.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

</div>

<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"> <%= @comment_restaurants.count %> 個已評論餐廳</h3>
    </div>
    <div class="panel-body">
      <%  @comment_restaurants.each  do |restaurant|%>
        <%= link_to restaurant_path(restaurant) do %>
          <div class="my-restaurant">
            <div><%= image_tag restaurant.image, class: " img-rounded" %></div>
            <%= restaurant.name %>
          </div>       
        <% end %>   
      <% end %>    
    </div>
  </div>  

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @favorited_restaurants.count %> 個收藏的餐廳</h3>
    </div>
    <div class="panel-body">
      <%  @favorited_restaurants.each  do |restaurant|%>
        <%= link_to restaurant_path(restaurant) do %>
          <div class="my-restaurant">
            <div><%= image_tag restaurant.image, class: " img-rounded" %></div>
            <%= restaurant.name %>
          </div>       
        <% end %>   
      <% end %>    
    </div>
  </div>  

</div>